from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

STEMS = "甲乙丙丁戊己庚辛壬癸"
BRANCHES = "子丑寅卯辰巳午未申酉戌亥"
SEXAGENARY_CYCLE = [
    STEMS[index % 10] + BRANCHES[index % 12]
    for index in range(60)
]
VALID_PILLARS = set(SEXAGENARY_CYCLE)
VALID_ZODIACS = set("鼠牛虎兔龍蛇馬羊猴雞狗豬")
VALID_DIRECTIONS_8 = {
    "正北", "東北", "正東", "東南",
    "正南", "西南", "正西", "西北",
}
VALID_SHA_DIRECTIONS = {
    "北", "東", "南", "西",
    "正北", "正東", "正南", "正西",
    "東北", "東南", "西北", "西南",
}

WEALTH_DIRECTION = {
    "甲": "東北",
    "乙": "東北",
    "丙": "西南",
    "丁": "西南",
    "戊": "正北",
    "己": "正北",
    "庚": "正東",
    "辛": "正東",
    "壬": "正南",
    "癸": "正南",
}

JOY_DIRECTION = {
    "甲": "東北",
    "乙": "西北",
    "丙": "西南",
    "丁": "正南",
    "戊": "東南",
    "己": "東北",
    "庚": "西北",
    "辛": "西南",
    "壬": "正南",
    "癸": "東南",
}

CLASH_ZODIAC = {
    "子": "馬",
    "丑": "羊",
    "寅": "猴",
    "卯": "雞",
    "辰": "狗",
    "巳": "豬",
    "午": "鼠",
    "未": "牛",
    "申": "虎",
    "酉": "兔",
    "戌": "龍",
    "亥": "蛇",
}

SHA_DIRECTION = {
    "子": "南",
    "丑": "東",
    "寅": "北",
    "卯": "西",
    "辰": "南",
    "巳": "東",
    "午": "北",
    "未": "西",
    "申": "南",
    "酉": "東",
    "戌": "北",
    "亥": "西",
}

OUTPUT_FIELDS = [
    "date",
    "edition",
    "source_pdf_page",
    "column_index",
    "source_crop",
    "crop_x0",
    "crop_y0",
    "crop_x1",
    "crop_y1",
    "column_warning",
    "date_mapping_source",
    "lunar_date_extracted",
    "day_pillar_extracted",
    "day_pillar_votes",
    "day_pillar_expected",
    "day_pillar_final",
    "pillar_check",
    "wealth_direction_extracted",
    "wealth_direction_expected",
    "wealth_check",
    "joy_direction_extracted",
    "joy_direction_expected",
    "joy_check",
    "clash_zodiac_extracted",
    "clash_zodiac_expected",
    "clash_check",
    "sha_direction_extracted",
    "sha_direction_expected",
    "sha_check",
    "ocr_pass_count",
    "required_fields_complete",
    "verification_status",
    "verification_notes",
    "extraction_method",
    "extraction_confidence",
    "reviewed_by_human",
    "verified_at",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Validate Yong Jing Tang candidates conservatively and route "
            "incomplete or conflicting records to exception review."
        )
    )
    parser.add_argument(
        "--candidates",
        default="extraction/yongjingtang_2026_candidates.jsonl",
        help="Combined candidate JSONL generated by 06_build_candidates.py.",
    )
    parser.add_argument(
        "--pillar-summary",
        default="ocr-results/pillars/pillar_ocr_summary.csv",
        help="Field-specific pillar OCR summary generated by 05c.",
    )
    parser.add_argument(
        "--ground-truth",
        default="",
        help=(
            "Optional human ground-truth CSV. Ground truth is used only for "
            "calibration fields and never converted into machine extraction."
        ),
    )
    parser.add_argument(
        "--output-dir",
        default="validation",
    )
    parser.add_argument(
        "--pages",
        default="",
        help="Optional comma-separated source PDF pages.",
    )
    parser.add_argument(
        "--edition",
        default="香港永經堂通勝 2026",
    )
    parser.add_argument(
        "--minimum-pillar-votes",
        type=int,
        default=2,
        help="Minimum OCR votes for a strong pillar check.",
    )
    parser.add_argument(
        "--minimum-machine-confidence",
        type=float,
        default=0.95,
        help="Final machine verification confidence threshold.",
    )
    return parser.parse_args()


def resolve(root: Path, value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else root / path


def as_int(value: Any, default: int = 0) -> int:
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


def as_float(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in {
        "1", "true", "yes", "y",
    }


def text(value: Any) -> str:
    return str(value or "").strip()


def parse_iso_date(value: str) -> datetime | None:
    value = text(value)
    if not value:
        return None
    try:
        return datetime.strptime(value, "%Y-%m-%d")
    except ValueError:
        return None


def first_candidate(record: dict[str, Any], field: str) -> str:
    values = record.get(field, [])
    if isinstance(values, list) and values:
        return text(values[0])
    return ""


def load_candidates(path: Path, requested_pages: set[int]) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Candidate JSONL not found: {path}")

    records = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(
                    f"Invalid JSON on line {line_number} of {path}: {error}"
                ) from error

            page = as_int(record.get("source_pdf_page"))
            if requested_pages and page not in requested_pages:
                continue
            records.append(record)

    return records


def load_pillar_summary(path: Path) -> dict[tuple[int, int], dict[str, str]]:
    if not path.exists():
        return {}

    result = {}
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            key = (
                as_int(row.get("source_pdf_page")),
                as_int(row.get("column_index")),
            )
            if key[0] and key[1]:
                result[key] = row
    return result


def load_ground_truth(path: Path | None) -> dict[tuple[int, int], dict[str, str]]:
    if path is None or not path.exists():
        return {}

    result = {}
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            key = (
                as_int(row.get("source_pdf_page")),
                as_int(row.get("column_index")),
            )
            if key[0] and key[1]:
                result[key] = row
    return result


def cycle_index(pillar: str) -> int | None:
    try:
        return SEXAGENARY_CYCLE.index(pillar)
    except ValueError:
        return None


def expected_from_pillar(pillar: str) -> dict[str, str]:
    if pillar not in VALID_PILLARS:
        return {
            "wealth": "",
            "joy": "",
            "clash": "",
            "sha": "",
        }

    stem = pillar[0]
    branch = pillar[1]
    return {
        "wealth": WEALTH_DIRECTION.get(stem, ""),
        "joy": JOY_DIRECTION.get(stem, ""),
        "clash": CLASH_ZODIAC.get(branch, ""),
        "sha": SHA_DIRECTION.get(branch, ""),
    }


def comparison_status(extracted: str, expected: str) -> str:
    if not extracted:
        return "missing"
    if not expected:
        return "not_checked"
    return "match" if extracted == expected else "conflict"


def build_sequence_expectations(
    records: list[dict[str, Any]],
    pillar_summary: dict[tuple[int, int], dict[str, str]],
) -> dict[tuple[int, int], str]:
    dated = []
    for record in records:
        page = as_int(record.get("source_pdf_page"))
        column = as_int(record.get("column_index"))
        date_value = parse_iso_date(record.get("date_candidate"))
        if date_value is None:
            continue

        key = (page, column)
        pillar_row = pillar_summary.get(key, {})
        extracted = text(pillar_row.get("day_pillar_top"))
        if not extracted:
            extracted = first_candidate(record, "day_pillar_candidates")

        if extracted in VALID_PILLARS:
            dated.append((date_value, key, extracted))

    if not dated:
        return {}

    anchor_date, _, anchor_pillar = max(
        dated,
        key=lambda item: (
            as_int(pillar_summary.get(item[1], {}).get("day_pillar_votes")),
            -abs((item[0] - dated[0][0]).days),
        ),
    )
    anchor_index = cycle_index(anchor_pillar)
    if anchor_index is None:
        return {}

    expectations = {}
    for record in records:
        page = as_int(record.get("source_pdf_page"))
        column = as_int(record.get("column_index"))
        date_value = parse_iso_date(record.get("date_candidate"))
        if date_value is None:
            continue
        offset = (date_value - anchor_date).days
        expectations[(page, column)] = SEXAGENARY_CYCLE[
            (anchor_index + offset) % 60
        ]
    return expectations


def confidence_score(
    pillar_check: str,
    pillar_votes: int,
    field_checks: list[str],
    column_warning: bool,
) -> float:
    score = 0.0

    if pillar_check == "match":
        score += 0.25
    elif pillar_check == "weak_match":
        score += 0.15

    if pillar_votes >= 2:
        score += 0.10
    elif pillar_votes == 1:
        score += 0.04

    for field_check in field_checks:
        if field_check == "match":
            score += 0.125

    if not column_warning:
        score += 0.10

    return round(min(score, 1.0), 3)


def main() -> None:
    args = parse_args()
    root = Path.cwd()

    candidates_path = resolve(root, args.candidates)
    pillar_summary_path = resolve(root, args.pillar_summary)
    output_dir = resolve(root, args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    ground_truth_path = (
        resolve(root, args.ground_truth)
        if args.ground_truth.strip()
        else None
    )

    requested_pages = {
        int(value.strip())
        for value in args.pages.split(",")
        if value.strip()
    }

    candidates = load_candidates(candidates_path, requested_pages)
    if not candidates:
        raise SystemExit("No candidate records were selected.")

    pillar_summary = load_pillar_summary(pillar_summary_path)
    ground_truth = load_ground_truth(ground_truth_path)
    sequence_expected = build_sequence_expectations(
        candidates,
        pillar_summary,
    )

    output_rows = []
    calibration_rows = []
    duplicate_counter = Counter(
        text(record.get("date_candidate"))
        for record in candidates
        if text(record.get("date_candidate"))
    )

    for record in sorted(
        candidates,
        key=lambda item: (
            text(item.get("date_candidate")),
            as_int(item.get("source_pdf_page")),
            as_int(item.get("column_index")),
        ),
    ):
        page = as_int(record.get("source_pdf_page"))
        column = as_int(record.get("column_index"))
        key = (page, column)

        date_value = text(record.get("date_candidate"))
        parsed_date = parse_iso_date(date_value)
        date_valid = parsed_date is not None
        duplicate_date = bool(
            date_value and duplicate_counter[date_value] > 1
        )

        pillar_record = pillar_summary.get(key, {})
        pillar_extracted = text(pillar_record.get("day_pillar_top"))
        pillar_votes = as_int(pillar_record.get("day_pillar_votes"))

        if not pillar_extracted:
            pillar_extracted = first_candidate(
                record,
                "day_pillar_candidates",
            )
            agreement = record.get("field_agreement", {}).get(
                "day_pillar_candidates",
                {},
            )
            pillar_votes = max(
                pillar_votes,
                as_int(agreement.get("top_votes")),
            )

        pillar_expected = sequence_expected.get(key, "")

        if not pillar_extracted:
            pillar_check = "missing"
        elif pillar_extracted not in VALID_PILLARS:
            pillar_check = "invalid"
        elif not pillar_expected:
            pillar_check = "not_checked"
        elif pillar_extracted != pillar_expected:
            pillar_check = "conflict"
        elif pillar_votes >= args.minimum_pillar_votes:
            pillar_check = "match"
        else:
            pillar_check = "weak_match"

        pillar_final = (
            pillar_extracted
            if pillar_check in {"match", "weak_match", "not_checked"}
            else ""
        )

        expected_values = expected_from_pillar(
            pillar_expected or pillar_final
        )

        lunar_extracted = first_candidate(
            record,
            "lunar_date_candidates",
        )
        wealth_extracted = first_candidate(
            record,
            "wealth_direction_candidates",
        )
        joy_extracted = first_candidate(
            record,
            "joy_direction_candidates",
        )
        clash_extracted = first_candidate(
            record,
            "clash_zodiac_candidates",
        )
        sha_extracted = first_candidate(
            record,
            "sha_direction_candidates",
        )

        wealth_check = comparison_status(
            wealth_extracted,
            expected_values["wealth"],
        )
        joy_check = comparison_status(
            joy_extracted,
            expected_values["joy"],
        )
        clash_check = comparison_status(
            clash_extracted,
            expected_values["clash"],
        )
        sha_check = comparison_status(
            sha_extracted,
            expected_values["sha"],
        )

        column_warning = truthy(record.get("column_warning"))
        ocr_pass_count = as_int(record.get("ocr_pass_count"))

        required_fields_complete = all(
            [
                date_valid,
                lunar_extracted,
                pillar_final,
                wealth_extracted,
                joy_extracted,
                clash_extracted,
                sha_extracted,
            ]
        )

        field_checks = [
            wealth_check,
            joy_check,
            clash_check,
            sha_check,
        ]

        extraction_confidence = confidence_score(
            pillar_check,
            pillar_votes,
            field_checks,
            column_warning,
        )

        conflict_reasons = []
        review_reasons = []

        if not date_valid:
            review_reasons.append("Missing or invalid Gregorian date")
        if duplicate_date:
            conflict_reasons.append("Duplicate Gregorian date")
        if column_warning:
            review_reasons.append("Crop or column warning")
        if not lunar_extracted:
            review_reasons.append("Missing extracted lunar date")
        if pillar_check in {"missing", "invalid"}:
            review_reasons.append("Missing or invalid extracted day pillar")
        elif pillar_check == "weak_match":
            review_reasons.append("Day pillar has only weak OCR support")
        elif pillar_check == "conflict":
            conflict_reasons.append("Extracted day pillar conflicts with sequence")

        for label, check in [
            ("wealth direction", wealth_check),
            ("joy direction", joy_check),
            ("clash zodiac", clash_check),
            ("sha direction", sha_check),
        ]:
            if check == "missing":
                review_reasons.append(f"Missing extracted {label}")
            elif check == "conflict":
                conflict_reasons.append(
                    f"Extracted {label} conflicts with generic rule"
                )

        if conflict_reasons:
            verification_status = "source_conflict"
        elif (
            required_fields_complete
            and pillar_check == "match"
            and all(check == "match" for check in field_checks)
            and not column_warning
            and extraction_confidence >= args.minimum_machine_confidence
        ):
            verification_status = "machine_verified"
        elif ocr_pass_count == 0:
            verification_status = "unclear_scan"
        else:
            verification_status = "needs_review"

        notes = conflict_reasons + review_reasons

        coordinates = record.get("crop_coordinates", {}) or {}
        output_row = {
            "date": date_value,
            "edition": args.edition,
            "source_pdf_page": page,
            "column_index": column,
            "source_crop": text(record.get("source_crop")),
            "crop_x0": as_int(coordinates.get("x0")),
            "crop_y0": as_int(coordinates.get("y0")),
            "crop_x1": as_int(coordinates.get("x1")),
            "crop_y1": as_int(coordinates.get("y1")),
            "column_warning": column_warning,
            "date_mapping_source": text(record.get("date_mapping_source")),
            "lunar_date_extracted": lunar_extracted,
            "day_pillar_extracted": pillar_extracted,
            "day_pillar_votes": pillar_votes,
            "day_pillar_expected": pillar_expected,
            "day_pillar_final": pillar_final,
            "pillar_check": pillar_check,
            "wealth_direction_extracted": wealth_extracted,
            "wealth_direction_expected": expected_values["wealth"],
            "wealth_check": wealth_check,
            "joy_direction_extracted": joy_extracted,
            "joy_direction_expected": expected_values["joy"],
            "joy_check": joy_check,
            "clash_zodiac_extracted": clash_extracted,
            "clash_zodiac_expected": expected_values["clash"],
            "clash_check": clash_check,
            "sha_direction_extracted": sha_extracted,
            "sha_direction_expected": expected_values["sha"],
            "sha_check": sha_check,
            "ocr_pass_count": ocr_pass_count,
            "required_fields_complete": required_fields_complete,
            "verification_status": verification_status,
            "verification_notes": " | ".join(notes),
            "extraction_method": (
                "crop_ocr+pillar_region_ocr+sequence_validation+generic_rule_comparison"
            ),
            "extraction_confidence": extraction_confidence,
            "reviewed_by_human": False,
            "verified_at": "",
        }
        output_rows.append(output_row)

        truth = ground_truth.get(key)
        if truth:
            expected_truth = text(truth.get("day_pillar"))
            if pillar_extracted == expected_truth and pillar_extracted:
                calibration_result = "correct"
            elif not pillar_extracted:
                calibration_result = "missing"
            else:
                calibration_result = "incorrect"

            calibration_rows.append(
                {
                    "source_pdf_page": page,
                    "column_index": column,
                    "date": date_value,
                    "ground_truth_pillar": expected_truth,
                    "ocr_pillar": pillar_extracted,
                    "ocr_votes": pillar_votes,
                    "result": calibration_result,
                }
            )

        print(
            f"Page {page}, column {column}, date={date_value or '--'}: "
            f"pillar={pillar_extracted or '--'} "
            f"expected={pillar_expected or '--'} "
            f"status={verification_status}"
        )

    validated_path = output_dir / "validated_candidates.csv"
    exceptions_path = output_dir / "exceptions.csv"
    publishable_path = output_dir / "publishable_candidates.csv"
    report_path = output_dir / "validation_report.json"
    calibration_path = output_dir / "ground_truth_calibration.csv"

    with validated_path.open(
        "w", encoding="utf-8-sig", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(output_rows)

    exceptions = [
        row
        for row in output_rows
        if row["verification_status"] in {
            "needs_review",
            "unclear_scan",
            "source_conflict",
        }
    ]
    with exceptions_path.open(
        "w", encoding="utf-8-sig", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(exceptions)

    publishable = [
        row
        for row in output_rows
        if row["verification_status"] in {
            "machine_verified",
            "human_verified",
        }
    ]
    with publishable_path.open(
        "w", encoding="utf-8-sig", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(publishable)

    if calibration_rows:
        calibration_fields = [
            "source_pdf_page",
            "column_index",
            "date",
            "ground_truth_pillar",
            "ocr_pillar",
            "ocr_votes",
            "result",
        ]
        with calibration_path.open(
            "w", encoding="utf-8-sig", newline=""
        ) as handle:
            writer = csv.DictWriter(
                handle,
                fieldnames=calibration_fields,
            )
            writer.writeheader()
            writer.writerows(calibration_rows)

    status_counts = Counter(
        row["verification_status"]
        for row in output_rows
    )
    pillar_counts = Counter(
        row["pillar_check"]
        for row in output_rows
    )

    report = {
        "candidate_records": len(output_rows),
        "status_counts": dict(status_counts),
        "pillar_check_counts": dict(pillar_counts),
        "exception_records": len(exceptions),
        "publishable_records": len(publishable),
        "duplicate_dates": sorted(
            date
            for date, count in duplicate_counter.items()
            if count > 1
        ),
        "minimum_pillar_votes": args.minimum_pillar_votes,
        "minimum_machine_confidence": args.minimum_machine_confidence,
        "important_note": (
            "Expected values are retained separately and never copied into "
            "extracted fields. Generic directions are comparison signals, "
            "not proof of printed publication values."
        ),
    }

    if calibration_rows:
        calibration_counts = Counter(
            row["result"]
            for row in calibration_rows
        )
        total = len(calibration_rows)
        correct = calibration_counts.get("correct", 0)
        report["ground_truth_calibration"] = {
            "total": total,
            "correct": correct,
            "missing": calibration_counts.get("missing", 0),
            "incorrect": calibration_counts.get("incorrect", 0),
            "accuracy_percent": round(
                (correct / total) * 100,
                1,
            ) if total else 0.0,
        }

    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(f"Validated candidates: {validated_path}")
    print(f"Exceptions: {exceptions_path}")
    print(f"Publishable candidates: {publishable_path}")
    print(f"Validation report: {report_path}")
    if calibration_rows:
        print(f"Ground-truth calibration: {calibration_path}")
    print(f"Validated records: {len(output_rows)}")
    print(f"Exceptions: {len(exceptions)}")
    print(f"Publishable records: {len(publishable)}")


if __name__ == "__main__":
    main()
